name: flutter_tomtom_navigation_example
description: Demonstrates how to use the flutter_tomtom_navigation plugin.

publish_to: 'none' 

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tomtom_navigation: ^0.0.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

# While the package is not available on pub.dev, we need an overridden version from Github.
dependency_overrides:
  flutter_tomtom_navigation:
    git:
      url: https://github.com/MatyasK/flutter_tomtom_navigation.git
      path: flutter_tomtom_navigation

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
