name: flutter_tomtom_navigation_android
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_tomtom_navigation_platform_interface:
    path: ../flutter_tomtom_navigation_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.tomtom.flutter_tomtom_navigation_android
        pluginClass: FlutterTomtomNavigationAndroidPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
