name: flutter_tomtom_navigation
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tomtom_navigation_android:
    path: ../flutter_tomtom_navigation_android
  flutter_tomtom_navigation_ios:
    path: ../flutter_tomtom_navigation_ios
  flutter_tomtom_navigation_platform_interface:
    path: ../flutter_tomtom_navigation_platform_interface  

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_tomtom_navigation_android
      ios:
        default_package: flutter_tomtom_navigation_ios

    

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
