name: flutter_tomtom_navigation_platform_interface
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
