name: flutter_tomtom_navigation_platform_interface
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  json_annotation: ^4.8.1
  uuid: ^4.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
